backend:
  - changed-files:
      - any-glob-to-any-file:
          - backend/**/*

frontend:
  - changed-files:
      - any-glob-to-any-file:
          - frontend/**/*

infrastructure:
  - changed-files:
      - any-glob-to-any-file:
          - Dockerfile
          - docker-compose.yml
          - .github/**/*

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**/*
          - "**.md"
